config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # resources :users
  root to: 'posts#index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :users, only: [:show]
  resources :musics
  resources :posts do
    resources :comments
  end
  resources :joins, only: %i[create destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates :content, presence: true, length: { maximum: 300 }
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  def index
    @post = Post.find(params[:post_id])
  end
  
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id
    respond_to do |format|
      if @comment.save
        format.js { render :index }
      else
        format.html { redirect_to post_path(@post), notice: '投稿できませんでした...' }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.destroy
      render :index 
    end
  end

  private
  # ストロングパラメーター
  def comment_params
    params.require(:comment).permit(:post_id, :content, :user_id)
  end
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: [post, comment]) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :コメント！ %>
    <%= form.text_area :content, class: "form-control" %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit '投稿する', class: "btn btn-default comment"%>
  </div>
<% end %>

app/views/comments/_index.html.erb
<h4 style="margin-top: 150px; margin-left: 650px;">コメント一覧</h4>
  <div class="comments", style="background-color: white;" >
    <% comments.each do |comment| %>
      <% if comment.id.present? %>
        <div class="comments__index">
          <h6><%= "#{comment.user.name}さん"%> <%= comment.created_at.to_formatted_s(:without_second) %></h6>  
          <h6><%= comment.content %></h6>
      <% end %>
      <% if comment.user == current_user %>
        <p><%= link_to 'コメントを削除する', post_comment_path(comment.post_id, comment.id), method: :delete, remote: true %></p>
      <% end %>
        </div>  
      <% end %>
  </div>
  

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'comments/index', { comments: @comment.post.comments, post: @comment.post }) %>")
$("textarea").val('')