config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # resources :users
  root to: 'posts#index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :users, only: [:show]
  resources :musics
  resources :posts do
    resources :comments
  end
  resources :joins, only: %i[create destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  has_many :togethers, dependent: :destroy
  has_many :musics, through: :togethers, source: :music
  has_many :comments, dependent: :destroy
  belongs_to :user

  validates :content, length: { maximum: 300 }

  scope :search_track, lambda { |artist_name|
    return if artist_name.blank?
    joins(:musics).where('artist_name like ?', "%#{artist_name}%")
  }
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  before_action :authenticate_user!,only: [:show, :destroy ]
  def new
    @post = Post.new
    @music = Music.find(params[:id])
  end

  def index
     if params[:artist_name].present?
      @posts = Post.search_track(params[:artist_name])
    else
      @posts = Post.all.order(created_at: 'DESC')
    end
  end

  def create
    @post = Post.new(content: params[:post][:content])
    @post.user_id = current_user.id
    if @post.save
      @together = Together.new(post_id: @post.id, music_id: params[:post][:music_id])
      @together.save
      flash[:success] = '新規投稿。'
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def destroy
    @post.destroy
    flash[:danger] = '投稿を削除しました。'
    redirect_to user_path(@post.user_id)
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
    @comment = @post.comments.build
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:track_name, :content, :user_id, :music_id)
  end
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/views/posts/index.html.erb
<%= form_with(model: @post, method: :get, local: true, url: posts_path) do |form| %>
  <%= form.text_field :artist_name, :placeholder => "アーティスト名", class:'form-control', style: "margin-top: 150px;"%>
  <%= form.submit '投稿検索', class: "btn btn-default post" %>
<% end %>

<div class="container">
  <div class="row">
    <% @posts.each do |post| %>
      <div class="col-xs-12 col-md-4">
        <% post.togethers.each do |together| %>
          <div class="card__post">
            <div class="card-header">
              <% if post.user.image.nil? %>
                <%= image_tag "default.jpg" %>
              <% else %>
                <%= image_tag(post.user.image.url, id: "index_my_image") if post.user.image && post.user.image.url  %>
              <% end %>
              <%= link_to "#{post.user.name}", user_path(id: post.user_id) %>
            </div>
            
            <div class="card-body" style="height: 30rem;">
              <%= together.music.artist_name %>
              <p><a href= <%= together.music.track_url %>>track:<%= together.music.track_name %></a></p>
              <p><a href= <%= together.music.album_url %>>album:<%= together.music.album_name %></a></p>
              <%= together.music.release_date%> 
              <%= image_tag together.music.image, :size => "285x285"%>
              <div class="audio-wrap" >
                <audio controls id="audio__post">
                  <source src= <%= together.music.preview_url %> type="audio/mp3">
                </audio>
              </div>
                <% if user_signed_in? %>
                  <%= link_to 'コメント',post_path(post.id)%>
                <% else %>
                  <%= link_to "login!でコメント", new_user_session_path%>
                <% end %>
                  <div id="post_date">
                    <%= post.created_at.to_formatted_s(:without_second) %>
                  </div>
            </div>
        <% end %>
            <div class="card-footer__index" style="height: 8rem;" >
              <%= simple_format(post.content) %>
            </div>
          </div>    
      </div>  
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
  <div class="card" style="width: 25rem;">
    <%= @music.artist_name %>
    <br>
    track:<%= @music.track_name %>
    <br>
    album:<%= @music.album_name %>
    <br>
    <%= @music.release_date %>
    <br>
    <br>
    <%= image_tag @music.image, :size => "400x400"%>
    <div class="card-footer" style="height: 1rem;">
      <%= form_with(model: @post, local:true) do |form| %>
        <%= form.text_area :content, class: 'form-control new' %>
        <%= form.hidden_field :music_id, value: @music.id %>
          <i class="fas fa-compact-disc ">
            <%= form.submit 'play it loud!!' %>
          </i>
          <%= link_to '選び直す',music_path(id: @music.id), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
    </div>
  </div>
      <% end %>

app/views/posts/show.html.erb
<h5 class='box line-break'style="margin-top: 200px; float: left; margin-left:100px; -100px; margin-right: -400px;">投稿コメント<br><%= @post.content%></h5>

<div class="container__comments">
  <p id="notice"><%= notice %></p>
    <!-- このcomments_areaというHTMLのidを取得して、そのdivの部分だけを更新する -->
    <div id="comments_area",style="margin-left:">
    
      <!-- 投稿されたコメント一覧をブログの詳細ページに表示するためのrender -->
      <%= render partial: 'comments/index', locals: { comments: @comments, post: @post } %>
    </div>
    <!-- コメント入力欄をブログの詳細ページに表示するためのrender -->
    <%= render partial: 'comments/form', locals: { comment: @comment, post: @post } %>
    <%= link_to '戻る', posts_path,class:"btn btn-default comment", style: "text-align: center;" %>
</div>

app/views/posts/show.utml.erb
<div class="container__show">
  <p id="notice"><%= notice %></p>

  <div class="show-text">
    <p><strong>内容</strong>：<%= @post.content %></p>
  </div>

  <p>コメント一覧（ここから下の内容が重要）</p>

  <!-- このcomments_areaというHTMLのidを取得して、そのdivの部分だけを更新する -->
  <div id="comments_area">
    <!-- 投稿されたコメント一覧をブログの詳細ページに表示するためのrender -->
    <%= render partial: 'comments/index', locals: { comments: @comments, post: @post } %>
  </div>

  <!-- コメント入力欄をブログの詳細ページに表示するためのrender -->
  <%= render partial: 'comments/form', locals: { comment: @comment, post: @post } %>

  <%= link_to '戻る', posts_path %>
</div>