config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # resources :users
  root to: 'posts#index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :users, only: [:show]
  resources :musics
  resources :posts do
    resources :comments
  end
  resources :joins, only: %i[create destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recoran</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <meta name="viewport" content="width=device-width">
  </head>

  <body>
  <header>
      <% if user_signed_in? %>
        <%= link_to "log out", destroy_user_session_path, method: :delete , class: "btn btn-default login" %>
      <% else %>
      <div id="user_session">
        <%= link_to "sign up", new_user_registration_path %>
        <%= link_to "log in", new_user_session_path, style: "margin-left: 15px;" %>
      </div>
      <% end %>
      <div class="title">
        <h4>recoran</h4>
      <div>
      <div id="button", style="margin-top: 30px;" >
        <div class="cp_tooltip">
          <%= link_to(musics_path) do %>
            <i class="fas fa-search fa-2x" ></i>
          <% end %>
            <span class="cp_tooltiptext">投稿作成</span>
        </div>
        <div class="cp_tooltip">
          <%= link_to(posts_path) do %>
            <i class="fas fa-compact-disc fa-2x" ></i>
          <% end %>
            <span class="cp_tooltiptext">投稿一覧</span>
          </div>
        <% if user_signed_in? %>
        <div class="cp_tooltip">
          <%= link_to user_path(id: current_user.id) do %>
            <i class="far fa-user-circle fa-2x"></i>
          <% end %>
            <span class="cp_tooltiptext">マイページ</span>
          </div>
        <% end %>
      </div>
      <% if notice %>
        <p class="alert alert-notice"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-error"><%= alert %></p>
      <% end %>
    </header>
  <%= yield %>
    <div id="back-to-top" style="position:fixed;right:25px;bottom:5px">
    <a href="#"><i class="fas fa-arrow-alt-circle-up fa-5x"></i></a></div>
  </body>
</html>